app1/urls.py
from django.urls import path
from . import views

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('home/', views.home, name='home'),  # Home page route
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),  # Logout route
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
]

app1/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AgriculturalOfficer(models.Model):
    aid = models.OneToOneField('User', models.DO_NOTHING, db_column='AID', primary_key=True)  # Field name made lowercase.
    region = models.CharField(db_column='Region', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'agricultural_officer'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Batch(models.Model):
    b_number = models.AutoField(db_column='B_Number', primary_key=True)  # Field name made lowercase.
    location = models.ForeignKey('Location', models.DO_NOTHING, db_column='Location_ID', blank=True, null=True)  # Field name made lowercase.
    sid = models.ForeignKey('Supplier', models.DO_NOTHING, db_column='SID', blank=True, null=True)  # Field name made lowercase.
    market = models.ForeignKey('MarketPlace', models.DO_NOTHING, db_column='MARKET_ID', blank=True, null=True)  # Field name made lowercase.
    product_amount = models.DecimalField(db_column='Product_Amount', max_digits=10, decimal_places=2)  # Field name made lowercase.
    sell = models.IntegerField(db_column='SELL', blank=True, null=True)  # Field name made lowercase.
    store = models.IntegerField(db_column='STORE', blank=True, null=True)  # Field name made lowercase.
    optimum_temperature_to_store = models.DecimalField(db_column='Optimum_temperature_to_store', max_digits=5, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    optimum_humidity_to_store = models.DecimalField(db_column='Optimum_humidity_to_store', max_digits=5, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    product_unit_price = models.DecimalField(db_column='Product_Unit_price', max_digits=10, decimal_places=2)  # Field name made lowercase.
    kg = models.DecimalField(db_column='KG', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    ton = models.DecimalField(db_column='TON', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    mon = models.DecimalField(db_column='MON', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    batch_description = models.TextField(db_column='Batch_Description', blank=True, null=True)  # Field name made lowercase.
    date_time_batch_created = models.DateTimeField(db_column='Date_Time_Batch_Created')  # Field name made lowercase.
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='User_ID', blank=True, null=True)  # Field name made lowercase.
    product = models.ForeignKey('Product', models.DO_NOTHING, db_column='PRODUCT_ID', blank=True, null=True)  # Field name made lowercase.
    hid = models.ForeignKey('Harvest', models.DO_NOTHING, db_column='HID', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'batch'


class BatchPurchaseRequest(models.Model):
    pid = models.OneToOneField('PurchaseRequest', models.DO_NOTHING, db_column='PID', primary_key=True)  # Field name made lowercase. The composite primary key (PID, B_Number) found, that is not supported. The first column is selected.
    b_number = models.ForeignKey(Batch, models.DO_NOTHING, db_column='B_Number')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'batch_purchase_request'
        unique_together = (('pid', 'b_number'),)


class Customer(models.Model):
    cid = models.OneToOneField('User', models.DO_NOTHING, db_column='CID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'customer'


class CustomerReqVisitToFarmer(models.Model):
    fid = models.OneToOneField('Farmer', models.DO_NOTHING, db_column='FID', primary_key=True)  # Field name made lowercase. The composite primary key (FID, CID, Visit_Date, Time_Slot) found, that is not supported. The first column is selected.
    cid = models.ForeignKey(Customer, models.DO_NOTHING, db_column='CID')  # Field name made lowercase.
    visit_date = models.DateField(db_column='Visit_Date')  # Field name made lowercase.
    time_slot = models.CharField(db_column='Time_Slot', max_length=100)  # Field name made lowercase.
    person_in_visit = models.CharField(db_column='Person_In_Visit', max_length=255, blank=True, null=True)  # Field name made lowercase.
    visit_charge_set_by_farmer = models.DecimalField(db_column='Visit_Charge_Set_By_Farmer', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'customer_req_visit_to_farmer'
        unique_together = (('fid', 'cid', 'visit_date', 'time_slot'),)


class Delivery(models.Model):
    pid = models.OneToOneField('PurchaseRequest', models.DO_NOTHING, db_column='PID', primary_key=True)  # Field name made lowercase. The composite primary key (PID, D_Time_DATE) found, that is not supported. The first column is selected.
    d_time_date = models.DateTimeField(db_column='D_Time_DATE')  # Field name made lowercase.
    delivery_status = models.CharField(db_column='Delivery_Status', max_length=50)  # Field name made lowercase.
    delivered_by = models.CharField(db_column='Delivered_By', max_length=255, blank=True, null=True)  # Field name made lowercase.
    is_pickedup = models.IntegerField(db_column='IS_PickedUp', blank=True, null=True)  # Field name made lowercase.
    is_on_the_way = models.IntegerField(db_column='IS_on_the_Way', blank=True, null=True)  # Field name made lowercase.
    fromwherepickup_loc = models.CharField(db_column='FromWherePickup_Loc', max_length=255, blank=True, null=True)  # Field name made lowercase.
    delivery_address = models.CharField(db_column='Delivery_Address', max_length=255, blank=True, null=True)  # Field name made lowercase.
    is_satisfy_customer = models.IntegerField(db_column='IS_satisfy_Customer', blank=True, null=True)  # Field name made lowercase.
    delivery_method = models.CharField(db_column='Delivery_Method', max_length=50, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'delivery'
        unique_together = (('pid', 'd_time_date'),)


class DistributorCompany(models.Model):
    did = models.OneToOneField('User', models.DO_NOTHING, db_column='DID', primary_key=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'distributor_company'


class DistributorCompanyDemandForProduct(models.Model):
    did = models.OneToOneField(DistributorCompany, models.DO_NOTHING, db_column='DID', primary_key=True)  # Field name made lowercase. The composite primary key (DID, PID, Demand_Date_Time) found, that is not supported. The first column is selected.
    pid = models.ForeignKey('Product', models.DO_NOTHING, db_column='PID')  # Field name made lowercase.
    demandamount = models.DecimalField(db_column='DemandAmount', max_digits=10, decimal_places=2)  # Field name made lowercase.
    ton = models.DecimalField(db_column='TON', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    mon = models.DecimalField(db_column='MON', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

app1/forms.py
from django import forms
from django import forms

from django import forms

class LoginForm(forms.Form):
    userid = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class SignupForm(forms.Form):
    
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField()
    phone = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput())
    Users_Type = [
        ('', 'Select a User Type'),  # This will be the default option, with an empty value
        ('a', 'Aggricultural Officer'),
        ('f', 'Farmer'),
        ('c', 'Customer'),
        ('s', 'Supplier'),
        ('n', 'Neutroshonist'),
        ('w', 'Wirehouse Manager'),
        ('d', 'Distributor Company'),
        ('r', 'Reatailer')

    ]
    
# models.CharField(db_column='F', max_length=1, blank=True, null=True)  # Field name made lowercase.
#      models.CharField(db_column='S', max_length=1, blank=True, null=True)  # Field name made lowercase.
#      = models.CharField(db_column='N', max_length=1, blank=True, null=True)  # Field name made lowercase.
#     = models.CharField(db_column='W', max_length=1, blank=True, null=True)  # Field name made lowercase.
#     = models.CharField(db_column='C', max_length=1, blank=True, null=True)  # Field name made lowercase.
#      = models.CharField(db_column='D', max_length=1, blank=True, null=True)  # Field name made lowercase.
#      = models.CharField(db_column='R', max_length=1, blank=True, null=True)  # Field name made lowercase.
#    

    Choosed_User_Type= forms.ChoiceField(
        choices=Users_Type,
        required=True,
        label=" User Type "
    )
    street = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'placeholder': 'Street'}))
    city = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'City'}))
    state = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'State'}))
    country = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Country'}))
    postalcode = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'placeholder': 'Postal Code'}))

app1/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory Management Dashboard</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }
        .container {
            margin-top: 50px;
        }
        .card {
            margin-bottom: 20px;
        }
        .card-header {
            background-color: #007bff;
            color: white;
        }
        .btn-primary {
            background-color: #007bff;
            border: none;
        }
        .btn-primary:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Harvest
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            <a href="{% url 'login' %}">
                <button class="btn btn-outline-success my-2 my-sm-0" type="button">
                    Logout
                </button>
            </a>
            

          </form>
        </div>
      </nav>

<div class="container">
    <h2 class="text-center">Welcome {{user.name }}  </h2>
    <h2 class="text-center">Inventory Management Dashboard</h2>

    <!-- Overview Section -->
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Total Items
                </div>
                <div class="card-body">
                    <h4 class="card-title">50</h4>
                    <p class="card-text">Total number of items in the inventory.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Low Stock Items
                </div>
                <div class="card-body">
                    <h4 class="card-title">5</h4>
                    <p class="card-text">Items with low stock level that need reordering.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Total Sales
                </div>
                <div class="card-body">
                    <h4 class="card-title">$1200</h4>
                    <p class="card-text">Total revenue from sales in the last month.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Inventory Table Section -->
    <div class="card">
        <div class="card-header">
            Inventory Items
            <button class="btn btn-primary float-right" data-toggle="modal" data-target="#addItemModal">Add New Item</button>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Item Name</th>
                        <th>Category</th>
                        <th>Stock Level</th>
                        <th>Price</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>Item A</td>
                        <td>Category 1</td>
                        <td>50</td>
                        <td>$10</td>
                        <td>
                            <button class="btn btn-sm btn-info">Edit</button>
                            <button class="btn btn-sm btn-danger">Delete</button>
                        </td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Item B</td>
                        <td>Category 2</td>
                        <td>20</td>
                        <td>$15</td>
                        <td>
                            <button class="btn btn-sm btn-info">Edit</button>
                            <button class="btn btn-sm btn-danger">Delete</button>
                        </td>
                    </tr>
                    <!-- Add more rows as needed -->
                </tbody>
            </table>
        </div>
    </div>

    <!-- Modal for Adding New Item -->
    <div class="modal fade" id="addItemModal" tabindex="-1" role="dialog" aria-labelledby="addItemModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addItemModalLabel">Add New Inventory Item</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="itemName">Item Name</label>
                            <input type="text" class="form-control" id="itemName" placeholder="Enter item name">
                        </div>
                        <div class="form-group">
                            <label for="itemCategory">Category</label>
                            <input type="text" class="form-control" id="itemCategory" placeholder="Enter category">
                        </div>
                        <div class="form-group">
                            <label for="itemStock">Stock Level</label>
                            <input type="number" class="form-control" id="itemStock" placeholder="Enter stock level">
                        </div>
                        <div class="form-group">
                            <label for="itemPrice">Price</label>
                            <input type="number" class="form-control" id="itemPrice" placeholder="Enter price">
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Save Item</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

app1/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        .login-container {
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 400px;
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        label {
            font-weight: bold;
            display: block;
            margin-top: 10px;
        }
        input[type="text"], input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 5px 0 15px;
            border-radius: 4px;
            border: 1px solid #ccc;
        }
        button {
            width: 100%;
            padding: 10px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
        button:hover {
            background-color: #45a049;
        }
        .form-footer {
            text-align: center;
            margin-top: 20px;
        }
        .form-footer a {
            color: #4CAF50;
            text-decoration: none;
        }
    </style>
</head>
<body>

    <div class="login-container">
        <h2>Login</h2>
        <h2>{{user.userid}} {{user.password}}</h2>
        <form method="POST">
           
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>

        <div class="form-footer">
            <p>Don't have an account? <a href="{% url 'signup' %}">Sign up here</a></p>
        </div>
    </div>

</body>
</html>

app1/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Signup</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

    <div class="container mt-5">
        <div class="signup-container">
            <h2 class="text-center mb-4">Create Account</h2>
            
            <!-- Display alert if form has errors -->
            {% if form.errors %}
                <div class="alert alert-danger">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

            <!-- Display last signed up user ID -->
            {% if last_user_id %}
                <div class="alert alert-info">
                    <strong>New user ID:</strong> {{ last_user_id }}
                </div>
            {% endif %}

            <!-- Form Starts Here -->
            <form method="POST" >
              
                <div class="form-group">
                    <label for="id_first_name">First Name</label>
                    {{ form.first_name }}
                </div>

                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    {{ form.last_name }}
                </div>

                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ form.email }}
                </div>

                <div class="form-group">
                    <label for="id_phone">Phone</label>
                    {{ form.phone }}
                </div>

                <div class="form-group">
                    <label for="id_password">Password</label>
                    {{ form.password }}
                </div>

                <div class="form-group">
                    <label for="id_Choosed_User_Type">User Type</label>
                    {{ form.Choosed_User_Type }}
                </div>

                <div class="form-group">
                    <label for="id_street">Street</label>
                    {{ form.street }}
                </div>

                <div class="form-group">
                    <label for="id_city">City</label>
                    {{ form.city }}
                </div>

                <div class="form-group">
                    <label for="id_state">State</label>
                    {{ form.state }}
                </div>

                <div class="form-group">
                    <label for="id_country">Country</label>
                    {{ form.country }}
                </div>

                <div class="form-group">
                    <label for="id_postalcode">Postal Code</label>
                    {{ form.postalcode }}
                </div>

                <button type="submit" class="btn btn-primary w-100">Sign Up</button>
            </form>

            <div class="form-footer text-center mt-3">
                <p>Already have an account? <a href="{% url 'login' %}">Login here</a></p>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>